### ISSUE TITLE
Add task runner

### ISSUE THREAD

**Issue by AndyCErnst** [Trishthedish/DuwamishApp#73]

**Comment by ivanoats** [comment]
I read and retweeted a recent survey that has Gulp winning the popularity contest. It's also faster than Grunt, and more well known than Brunch or Broccoli.  Any objections to Gulp?

**Comment by ivanoats** [comment]
oh sorry, I just saw https://github.com/Trishthedish/DuwamishApp/pull/78 . Grunt is fine with me unless the build time starts to get too long.
