### ISSUE TITLE
Include URL in README

### ISSUE THREAD

**Issue by kerrizor** [Trishthedish/DuwamishApp#81]
Is there a public URL?

**Comment by ivanoats** [comment]
Yes, http://www.standwithduwamish.com This should be put in the README and also the summary info at the top of the repo. @Trishthedish can you give me membership to this repo now that I'm helping out?

And /me waves Hi Kerri! :smile:

**Comment by kerrizor** [comment]
I can submit a PR with that. <3

**Comment by Trishthedish** [comment]
Hi @kerrizor! Thanks for your assistance. Would you like to join the team? How'd you hear about the project?

**Comment by kerrizor** [comment]
Just emailed you, @Trishthedish :)

URL added in #82
